name = "abhishekrai-portfolio"
main = "src/worker.js"
compatibility_date = "2026-07-17"

# Configure static assets directory to be served by the Worker
[assets]
directory = "./public"
binding = "ASSETS"
